"""
A set of stateless plotting functions to produce common graphs
based on datasets generated by scenariohandler objects although not required.

Datasets are expected to have a column level named "Technology" and works well with
multi-index column features available in pandas. In general, the plotting functions can process dataframes
with up to 3 column levels ["Area", "Technology", "Generator"].

@author: Micah Webb
"""
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patheffects as path_effects
import matplotlib.dates as mdates
import pandas as pd
from loguru import logger

from .utils import *
import math
from ..config import config

from .core import plot_stacked_component_area, plot_stacked_component_bar


# TODO move to config
curt_tech = config.curtailable_tech

MW_to_TW = 1000000
MW_to_GW = 1000

def add_line(df,var,ax,style):
    if var in df.columns:
        xmin = [i-0.25 for i in range(len(df.index))]
        xmax = [i+0.25 for i in range(len(df.index))]
    ax.hlines(y=df[var].values, color='Black', linestyle=style, xmin=xmin, xmax=xmax, label=var)


def make_facet_axes(num_plots, **kwargs):
    grid_size = math.ceil(math.sqrt(num_plots))

    fig, axs = plt.subplots(grid_size, grid_size, **kwargs)

    axs = trim_axs(axs, num_plots )

    return fig, axs




# assumes a frame with generation and demand columns (no multi-index)
def plot_dispatch_stack_bar(df, include_net_load=False, include_total_load=False, ax=None,
                            palette=None, backend=None, **kwargs):

    """
    Plots a bar chart of the Dispatch Stack dataframe

    expects a dataframe with columns of standard technology types (Wind, PV, etc.)

    y - axis: Total Generation and Demand* in TWh
    x - axis: The index of the dataframe. (examples: Months of the year, Year, ISOs, Balancing Areas)

    * Plots Demand if available
    """

    #Convert to TWh
    df_tw = df/MW_to_TW

    drop_cols = [col for col in config.load_columns if col in df_tw.columns]
    df_tw_stack = df_tw.drop(columns=drop_cols)

    horizontal = kwargs.pop('kind', 'bar') == 'barh'
    title = kwargs.pop("title", "Dispatch Stack")

    if ax is not None:
        kwargs['ax'] = ax

    result = plot_stacked_component_bar(
        df_tw_stack, horizontal=horizontal,
        palette=palette, backend=backend, **kwargs,
    )

    # Post-render formatting — use backend helpers when available
    from .backends import get_backend
    be = get_backend(backend)
    be.set_title(result, title)

    if not horizontal:
        be.set_ylabel(result, "Generation and Demand (TWh)")
    else:
        be.set_xlabel(result, "Generation and Demand (TWh)")

    return result


# expects a dataframe with generation technologies and demand as columns and timestamps as index
def plot_stacked_area_window(df, ax=None, include_net_load=False, include_total_load=False,
                             palette=None, backend=None, **kwargs):

    """
        Plots a stacked area chart of the various technology types.

        Generally reserved for plotting raw time windows of dataframes (no monthly or annual aggregates)
        Called by the plot_peak_demand_window() and plot_min_demand_window().

        x-axis: Dataframe index, usually timestamps
        y-axis: Power by Dispatch Technology in GW, (Wind, PV, etc)

    """

    if ax is not None:
        kwargs['ax'] = ax

    df_gw = df/MW_to_GW

    result = plot_stacked_component_area(df_gw,
                                linewidth=0,
                                include_total_load=include_total_load,
                                include_net_load=include_net_load,
                                palette=palette,
                                backend=backend,
                                **kwargs)

    return result

# expects a dataframe with generation technologies and demand as columns and timestamps as index
def plot_peak_demand_window(df, window_delta=3, ax=None, return_frame=False,
                            palette=None, backend=None, **kwargs):


    """
        Plots the stacked area chart for the peak demand window.
        Finds the index of the max demand and calls the plot_stacked_area() method

        Annotates the point of peak demand.

        x-axis: Dataframe index, usually timestamps
        y-axis: Power by Dispatch Technology in GW, (Wind, PV, etc)

    """

    if ax == None:
        ax = plt.axes()

    dfg = df.T.groupby( level='Technology').sum().T

    delta = pd.Timedelta(days=window_delta)

    idx_max = dfg[config.total_load_alias].idxmax()

    dfg_window = dfg.loc[idx_max.round('D')-delta:idx_max.round('D')+delta:]

    max_demand_val = dfg_window[config.total_load_alias].loc[idx_max]/MW_to_GW
    max_dispatch_val = dfg_window[[col for col in dfg.columns if col not in config.load_columns]].sum(axis=1).max()/MW_to_GW

    max_y = max(max_demand_val, max_dispatch_val)

    chart = plot_stacked_area_window(dfg_window, ax=ax, include_total_load=True,
                                     palette=palette, backend=backend, **kwargs)

    # Post-render formatting via backend helpers
    from .backends import get_backend
    be = get_backend(backend)
    annotate_timestamp = idx_max - pd.Timedelta(days=2)
    be.add_annotation(chart, f'Peak Demand: \n{max_demand_val:.2f} GW',
                      xy=(idx_max, max_demand_val),
                      xytext=(annotate_timestamp, max_y*1.1))
    be.set_title(chart, "Period of Peak Demand")
    be.set_ylim(chart, 0, max_y*1.3)
    be.set_xlim(chart, idx_max.round('D')-delta, idx_max.round('D')+delta)
    if return_frame:
        return chart, dfg_window
    else:
        return chart


def plot_min_demand_window(df, window_delta=3, ax=None, return_frame=False, load_column=None,
                           palette=None, backend=None, **kwargs):


    """
        Plots the stacked area chart for the minimum demand window.
        Finds the index of the minimum demand and calls the plot_stacked_area() method

        Annotates the point of minimum demand.

        x-axis: Dataframe index, usually timestamps
        y-axis: Power by Dispatch Technology in GW, (Wind, PV, etc)

    """

    if ax == None:
        ax = plt.axes()

    delta = pd.Timedelta(days=window_delta)
    dfg = df.T.groupby(level='Technology').sum().T

    idx_min = dfg[config.total_load_alias].idxmin()

    dfg_window = dfg.loc[str(idx_min.round('D')-delta):str(idx_min.round('D')+delta)]


    min_demand_val = dfg_window[config.total_load_alias].loc[idx_min]/MW_to_GW
    max_demand_val = dfg_window[config.total_load_alias].max()/MW_to_GW
    max_dispatch_val = dfg_window[[col for col in dfg.columns if col  not in config.load_columns]].max(axis=1).max()/MW_to_GW
    max_y = max(max_demand_val, max_dispatch_val)


    chart = plot_stacked_area_window(dfg_window, ax=ax, palette=palette, backend=backend, **kwargs)

    from .backends import get_backend
    be = get_backend(backend)
    annotate_timestamp = idx_min - pd.Timedelta(days=2)
    be.add_annotation(chart, f'Minimum {config.total_load_alias}: \n{min_demand_val:.2f} GW',
                      xy=(idx_min, min_demand_val),
                      xytext=(annotate_timestamp, max_y*1.1))
    be.set_title(chart, f"Period of Minimum {config.total_load_alias}")
    be.set_ylim(chart, 0, max_y*1.5)
    be.set_xlim(chart, idx_min.round('D')-delta, idx_min.round('D')+delta)

    if return_frame:
        return chart, dfg_window
    else:
        return chart



def plot_dispatch_window(dispatch, timestamp, window_delta=3, annotate=True, annotate_text="", return_frame=False, ax=None, format_ticks=True,
                         palette=None, backend=None, **kwargs):

    # Let's assume we are always annotating demand.

    delta = pd.Timedelta(days=window_delta)
    dfg = dispatch.T.groupby(level='Technology').sum().T

    dfg_window = dfg.loc[timestamp.date()-delta:timestamp.date()+delta]

    if ax is not None:
        kwargs['ax'] = ax

    chart = plot_stacked_area_window(dfg_window, palette=palette, backend=backend, **kwargs)

    from .backends import get_backend
    be = get_backend(backend)

    # Tick formatting — only for matplotlib backend
    if format_ticks and be.name == "static":
        chart.xaxis.set_major_locator(mdates.DayLocator())
        chart.xaxis.set_major_formatter(mdates.DateFormatter('%b-%d\n%Y'))
        chart.xaxis.set_minor_locator(mdates.HourLocator(byhour=[6,12,18]))
        chart.xaxis.set_minor_formatter(mdates.DateFormatter(''))

        labels = chart.get_xticklabels()
        chart.set_xticklabels(labels, rotation=0, ha='center')
        chart.grid(visible=True,which='both', axis='x' ,alpha=0.2)

    # scale the frame
    max_demand_val = dfg_window[config.total_load_alias].max()/MW_to_GW
    max_dispatch_val = dfg_window[[col for col in dfg_window.columns if col not in config.load_columns]].max(axis=1).max()/MW_to_GW
    max_y = max(max_demand_val, max_dispatch_val)

    # annotate
    if annotate:
        annotate_loc = timestamp - pd.Timedelta(days=2)
        demand_val = dfg_window.loc[timestamp][config.total_load_alias]/MW_to_GW
        be.add_annotation(chart, annotate_text,
                          xy=(timestamp, demand_val),
                          xytext=(annotate_loc, max_y*1.3))

    be.set_xlim(chart, dfg_window.index.min(), dfg_window.index.max())
    if return_frame:
        return chart, dfg_window
    else:
        return chart

def facet_dispatch_windows(dispatch, timestamps:list, titles:list, window_delta=3, return_frame=False,
                           palette=None, backend=None, **kwargs):
    """
        takes in a dispatch dataframe and a list of timestamps,
        and returns a facet plot of those timestamps

    """
    num_plots = len(timestamps)
    fig, axs = make_facet_axes(len(timestamps), figsize=(num_plots*window_delta*2, num_plots*2), **kwargs)
    num_rows, num_cols = fig.axes[0].get_subplotspec().get_gridspec().get_geometry()

    unique_tech = dispatch.columns.get_level_values(level='Technology').unique()
    patches = prepare_tech_legend(unique_tech)

    axs=axs.reshape(-1)[0:num_plots]
    frames = []
    for i, time in enumerate(timestamps):

        ax = axs[i]
        if len(titles)>=i:
            title = titles[i]
            ax.set_title(title)

        if return_frame:
            ax, df = plot_dispatch_window(dispatch, time, window_delta, ax=ax, annotate=False,
                                          return_frame=return_frame, format_ticks=False,
                                          palette=palette, backend=backend)
            frames.append(df)
        else:
            ax = plot_dispatch_window(dispatch, time, window_delta, ax=ax, annotate=False,
                                      return_frame=return_frame, format_ticks=False,
                                      palette=palette, backend=backend)
        ax.get_legend().remove()
        if i == num_cols - 1:

            ax.legend(handles=patches, bbox_to_anchor=[1,1])
    if return_frame:
        df = pd.concat(frames)
        return fig, axs, df
    else:
        return fig, axs


## Common Reports


## PLOTTING Functions

# Expects dataframe with a column for each tech type [Nuclear, Coal, Gas, Hydro, etc.]
# Expects all timestamps available
def plot_annual_system_dispatch_stack(df, ax=None, return_frame=False,
                                      palette=None, backend=None, **kwargs):

    """
    Plots a stacked bar of the various Power Generation technologies in the dataframe

    If multi-year, plots a bar for each year.

    Expects a DateTimeIndex and Resamples the dataframe to Yearly and calls,
    plot_dispatch_stack_bar() method.

    y-axis: Generation & Demand (TWh)
    x-axis: Year in %Y format.

    """

    system_dispatch = df.T.groupby(level="Technology").sum().T
    system_dispatch_annual = system_dispatch.groupby(system_dispatch.index.year).sum()
    system_dispatch_annual.index = system_dispatch_annual.index.astype(str)

    if ax is not None:
        kwargs['ax'] = ax

    chart = plot_dispatch_stack_bar(system_dispatch_annual,
                                    palette=palette, backend=backend, **kwargs)

    from .backends import get_backend
    be = get_backend(backend)
    be.set_title(chart, "System - Annual Dispatch Stack")

    if return_frame:
        return chart, system_dispatch_annual
    else:
        return chart



# Single figure with stacked bars for each month
def plot_monthly_system_dispatch_stack(df, ax=None, return_frame=False,
                                       palette=None, backend=None, **kwargs):

    """
    Plots a stacked bar of the various Power Generation technologies

    Expects a DateTimeIndex and Resamples the dataframe to monthly and calls,
    plot_dispatch_stack_bar() method.

    y-axis: Generation & Demand (TWh)
    x-axis: Year in %B format.
    """

    system_dispatch_monthly = df.T.groupby( level="Technology").sum().T.resample("ME").sum()
    system_dispatch_monthly.index = system_dispatch_monthly.index.strftime('%B')

    if ax is not None:
        kwargs['ax'] = ax

    chart = plot_dispatch_stack_bar(system_dispatch_monthly,
                                    palette=palette, backend=backend, **kwargs)

    from .backends import get_backend
    be = get_backend(backend)
    be.set_title(chart, "System - Monthly Dispatch Stack")

    if return_frame:
        return chart, system_dispatch_monthly
    else:
        return chart


def plot_mean_hourly_dispatch(dispatch, return_frame=False,
                              palette=None, backend=None, **kwargs):

    dispatch_hour_mean = dispatch.groupby(dispatch.index.hour).mean().T.groupby(level='Technology').sum().T
    chart = plot_stacked_area_window(dispatch_hour_mean,
                                     palette=palette, backend=backend, **kwargs)

    if return_frame:
        return chart, dispatch_hour_mean
    else:
        return chart



# Single figure with stacked bars for each Area
def plot_annual_area_dispatch_stack(df, ax=None, return_frame=False,
                                    palette=None, backend=None, **kwargs):

    """
    Plots a stacked bar of the various Power Generation technologies for each Area
    within the MultiIndex column.

    If Multi-Year, aggregates all years together.

    y-axis: Generation & Demand (TWh)
    x-axis: Area Name

    """

    zonal_dispatch = df.T.groupby(level=["Area","Technology"]).sum().T
    zonal_dispatch_annual = zonal_dispatch.sum().unstack()

    if ax is not None:
        kwargs['ax'] = ax

    chart = plot_dispatch_stack_bar(zonal_dispatch_annual,
                                    palette=palette, backend=backend, **kwargs)

    from .backends import get_backend
    be = get_backend(backend)
    be.set_title(chart, "Area - Annual Dispatch Stack")

    if return_frame:
        return chart, zonal_dispatch_annual
    else:
        return chart

### Curtailment Stack
def plot_annual_system_curtailment_stack(df, ax=None, return_frame=False,
                                         palette=None, backend=None, **kwargs):

    """
    Plots a stacked bar of the various various Curtailable Power Generation technologies (Wind, PV)

    If multi-year, plots a bar for each year.

    Expects a DateTimeIndex and Resamples the dataframe to Yearly and calls,
    plot_dispatch_stack_bar() method.

    y-axis: Generation & Demand (TWh)
    x-axis: Year in %Y format.

    """

    curtailment_tech = df.T.groupby(level='Technology').sum().T
    curtailment_tech_annual = curtailment_tech.groupby(curtailment_tech.index.year).sum()

    if ax is not None:
        kwargs['ax'] = ax

    chart = plot_dispatch_stack_bar(curtailment_tech_annual,
                                    palette=palette, backend=backend, **kwargs)

    from .backends import get_backend
    be = get_backend(backend)
    be.set_title(chart, "System - Annual Curtailment Stack")
    be.set_ylabel(chart, "Curtailment (TWh)")

    if return_frame:
        return chart, curtailment_tech_annual
    else:
        return chart

def plot_monthly_system_curtailment_stack(df, ax=None, return_frame=False,
                                          palette=None, backend=None, **kwargs):

    """
    Plots a stacked bar of the various Curtailable Power Generation technologies (Wind, PV)

    Expects a DateTimeIndex and Resamples the dataframe to monthly and calls,
    plot_dispatch_stack_bar() method.

    y-axis: Generation & Demand (TWh)
    x-axis: Year in %B format.

    """

    curtailment_tech_monthly = df.T.groupby(level='Technology').sum().T.resample("ME").sum()
    curtailment_tech_monthly.index = curtailment_tech_monthly.index.strftime("%B")

    if ax is not None:
        kwargs['ax'] = ax

    chart = plot_dispatch_stack_bar(curtailment_tech_monthly,
                                    palette=palette, backend=backend, **kwargs)

    from .backends import get_backend
    be = get_backend(backend)
    be.set_title(chart, "System - Monthly Curtailment Stack")
    be.set_ylabel(chart, "Curtailment (TWh)")

    if return_frame:
        return chart, curtailment_tech_monthly
    else:
        return chart


def plot_annual_area_curtailment_stack(df, ax=None, return_frame=False,
                                       palette=None, backend=None, **kwargs):

    """
    Expects a Area curtailment dataset with a MultiIndex column of 2 levels.
    level 0: Area (e.g. balancing area, ISO, Interconnect, any group of generators)
    level 1: Technology type (e.g. PV, Wind, Offshore-Wind)

    Returns a stacked bar plot with varying colors for each technology:
    x-axis: Area (e.g. balancing area, ISO, Interconnect, any group of generators)
    y-axis: Total Geneartion (TWh)
    """

    curt_tech_area_annual = df.sum().unstack(level="Technology").fillna(0)

    if ax is not None:
        kwargs['ax'] = ax

    chart = plot_dispatch_stack_bar(curt_tech_area_annual,
                                    palette=palette, backend=backend, **kwargs)

    from .backends import get_backend
    be = get_backend(backend)
    be.set_title(chart, "Area - Annual Curtailment Stack")
    be.set_ylabel(chart, "Generation (TWh)")

    if return_frame:
        return chart, curt_tech_area_annual
    else:
        return chart


def facet_area_dispatch_generic(dispatch, plot_func, palette=None, backend=None):

    areas = dispatch.columns.get_level_values(level='Area').unique()
    technologies = dispatch.columns.get_level_values(level='Technology').unique()

    tech_patches = prepare_tech_legend(technologies)
    num_areas = len(areas)

    grid_size = math.ceil(math.sqrt(num_areas))

    num_rows = math.floor(num_areas/grid_size)

    fig, axs = plt.subplots(grid_size, grid_size, figsize=(grid_size*2.0, grid_size*2.0), sharex=False, sharey=False, dpi=grid_size*100)

    axs = trim_axs(axs, num_areas-1)

    if num_areas > 1:
        axs_flat = axs.reshape(-1)[0:num_areas-1]
    else:
        axs_flat = [axs]

    for i, ax in enumerate(axs_flat):

        try:
            ax.spines[['right', 'top', 'bottom']].set_visible(False)
            plot_func(dispatch[areas[i]], ax=ax, palette=palette, backend=backend)
            ax.set_title("{}".format(areas[i]))
            ax.get_legend().remove()


            if i < num_areas - grid_size:
                ax.set_xlabel(None)
                ax.set_xticks([])

            # put ylabel in middle row left column
            if i % grid_size != 0:
                ax.set_ylabel(None)
        except Exception as e:
            logger.warning(f"Failed to plot for Area {areas[i]}")
            logger.warning(e)

    fig.set_size_inches(grid_size*5, num_rows*5)
    axs_flat[grid_size-1].legend(handles=tech_patches, loc='upper right', bbox_to_anchor=[1.6, 1.05])
    return fig, axs




def facet_area_monthly_dispatch(dispatch: pd.DataFrame, palette=None, backend=None):

    plot_func = plot_monthly_system_dispatch_stack

    fig, axs = facet_area_dispatch_generic(dispatch=dispatch, plot_func=plot_func,
                                           palette=palette, backend=backend)

    return fig, axs


def facet_area_annual_dispatch(dispatch: pd.DataFrame, palette=None, backend=None):

    plot_func = plot_annual_system_dispatch_stack

    fig, axs = facet_area_dispatch_generic(dispatch=dispatch, plot_func=plot_func,
                                           palette=palette, backend=backend)

    return fig, axs


def facet_area_dispatch_window(dispatch: pd.DataFrame, palette=None, backend=None):

    areas = dispatch.columns.get_level_values(level='Area').unique()
    num_areas = len(areas)

    grid_size = math.ceil(math.sqrt(num_areas))

    fig, axs = plt.subplots(grid_size, grid_size, figsize=(grid_size*1.2, grid_size*1.2), sharex=True, sharey=False)

    axs = trim_axs(axs, num_areas -1 )

    if num_areas > 1:
        axs_flat = axs.reshape(-1)[0:num_areas-1]
    else:
        axs_flat = [axs]

    for i, ax in enumerate(axs_flat):

        plot_stacked_area_window(dispatch[areas[i]], ax=ax,
                                 palette=palette, backend=backend)
        ax.set_title(areas[i])

        ## TODO add option to get full technology legend even if tech isn't present.
        ax.get_legend().remove()

        # if axes on bottom row
        if i < (grid_size-1)**2:
            ax.set_xlabel(None)
            ax.set_xticks([])
            ax.spines[['right', 'top', 'bottom']].set_visible(False)

        # if axes on right hand side, show legend
        #if i != grid_size-1:
        #    ax.get_legend().remove()

        # put ylabel in middle row left column
        if i != grid_size*math.floor(grid_size/2):
            ax.set_ylabel(None)


        #if axes on left hand side, show ylabel

    return fig, ax