sienna_standard_map = {
    "BA": "BESS",
    "CA_NATURAL_GAS": "Gas-CT",
    "CC_NATURAL_GAS": "Gas-CC",
    "CC_MUNICIPAL_WASTE": "Gas-CC",
    "CC_OTHER": "Gas-CC",
    "CT_COAL": "Coal",
    "CT_DISTILLATE_FUEL_OIL": "o-g-s",
    "CT_MUNICIPAL_WASTE": "Biopower",
    "CT_NATURAL_GAS": "Gas-CT",
    "CT_OTHER": "Gas-CT",
    "CT_RESIDUAL_FUEL_OIL": "o-g-s",
    "CT_WASTE_OIL": "o-g-s",
    "GT_MUNICIPAL_WASTE": "Biopower",
    "GT_NATURAL_GAS": "Gas-CT",
    "GT_OTHER": "Other",
    "GT_WOOD_WASTE": "Biopower",
    "HY": "Hydro",
    "IC_DISTILLATE_FUEL_OIL": "o-g-s",
    "IC_MUNICIPAL_WASTE": "Biopower",
    "IC_NATURAL_GAS": "Gas-CT",
    "IC_OTHER": "Other",
    "OT": "Other",
    "OT_COAL": "Coal",
    "OT_MUNICIPAL_WASTE": "Biopower",
    "OT_NATURAL_GAS": "o-g-s",
    "OT_NUCLEAR": "Nuclear",
    "OT_OTHER": "Other",
    "OT_WASTE_COAL": "Coal",
    "PS_Other": "PS",
    "PVe": "PV",
    "ST_COAL": "Coal",
    "ST_DISTILLATE_FUEL_OIL": "o-g-s",
    "ST_GEOTHERMAL": "Geothermal",
    "ST_MUNICIPAL_WASTE": "Biopower",
    "ST_NATURAL_GAS": "o-g-s",
    "ST_NUCLEAR": "Nuclear",
    "ST_OTHER": "Other",
    "ST_PETROLEUM_COKE": "o-g-s",
    "ST_RESIDUAL_FUEL_OIL": "o-g-s",
    "ST_WASTE_COAL": "Coal",
    "ST_WASTE_OIL": "o-g-s",
    "WS": "Offshore Wind",
    "WT": "Land-based Wind",
    "Demand": "Demand",
}


plexos_map_simple = {
    "ReEDS_battery": "Storage",
    "ReEDS_biopower": "Biopower",
    "ReEDS_coal-igcc_coal-ccs_mod": "Coal-CCS",
    "ReEDS_coal-new_coal-ccs_mod": "Coal-CCS",
    "ReEDS_coaloldscr_coal-ccs_mod": "Coal-CCS",
    "ReEDS_distpv": "PV",
    "ReEDS_dupv": "dPV",
    "ReEDS_gas-cc_gas-cc-ccs_mod": "Gas-CCS",
    "ReEDS_hyded": "Hydro",
    "ReEDS_hydud": "Hydro",
    "ReEDS_hydend": "Hydro",
    "ReEDS_lfill-gas": "Biopower",
    "ReEDS_gas-cc_re-cc": "H2-CC",
    "ReEDS_gas-ct_re-ct": "H2-CT",
    "ReEDS_re-cc": "H2-CC",
    "ReEDS_upv": "PV",
    "ReEDS_wind-ons": "Land-based Wind",
    "nuclear": "Nuclear",
    "ReEDS_can-imports": "Imports",
    "ReEDS_hydund": "Hydro",
    "ReEDS_pumped-hydro": "Storage",
    "ReEDS_re-ct": "H2-CT",
    "ReEDS_wind-ofs": "Offshore Wind",
    "ReEDS_beccs_mod": "BECCS",
    "ReEDS_geothermal": "Geothermal",
    "ReEDS_gas-cc-ccs_mod": "Gas-CCS",
    "caes": "Storage",
    "biopower": "Biopower",
    "coalolduns": "Coal",
    "ReEDS_nuclear": "Nuclear",
    "gas-cc": "Gas-CC",
    "gas-ct": "Gas-CT",
    "ReEDS_gas-cc": "Gas-CC",
    "ReEDS_gas-ct": "Gas-CT",
    "coaloldscr": "Coal",
    "o-g-s": "Oil-Gas-Steam",
    "ReEDS_o-g-s": "Oil-Gas-Steam",
    "ReEDS_coal-new": "Coal",
    "ReEDS_coaloldscr": "Coal",
    "coal-new": "Coal",
    "ReEDS_csp-ns": "Other",
    "coal-igcc": "Coal",
    "ReEDS_coalolduns_coal-ccs_mod": "Coal-CCS",
    "ReEDS_dupv": "dPV",
    "battery": "Storage",
    "battery-4": "Storage",
    "battery_4": "Storage",
    "biopower": "Biopower",
    "coal-igcc_coal-ccs_mod": "Coal-CCS",
    "coal-new_coal-ccs_mod": "Coal-CCS",
    "coaloldscr_coal-ccs_mod": "Coal-CCS",
    "distpv": "dPV",
    "dupv": "dPV",
    "gas-cc_gas-cc-ccs_mod": "Gas-CCS",
    "Hydro": "Hydro",
    "hyded": "Hydro",
    "hydud": "Hydro",
    "hydend": "Hydro",
    "lfill-gas": "Biopower",
    "gas-cc_re-cc": "H2-CC",
    "gas-ct_re-ct": "H2-CT",
    "re-cc": "H2-CC",
    "upv": "PV",
    "wind-ons": "Land-based Wind",
    "can-imports": "Imports from Canada",
    "hydund": "Hydro",
    "pumped-hydro": "Storage",
    "re-ct": "H2-CT",
    "wind-ofs": "Offshore Wind",
    "beccs_mod": "BECCS",
    "beccs": "BECCS",
    "geothermal": "Geothermal",
    "gas-cc-ccs_mod": "Gas-CCS",
    "caes": "Storage",
    "biopower": "Biopower",
    "coalolduns": "Coal",
    "coal-new": "Coal",
    "coaloldscr": "Coal",
    "csp-ns": "Other",
    "coalolduns_coal-ccs_mod": "Coal-CCS",
    "dupv": "dPV",
    "h2-ct": "H2-CT",
    "hydnpnd": "Hydro",
    "gas-cc-ccs": "Gas-CCS",
    "geohydro": "Geothermal",
    "undisc_pflash_1": "Geothermal",
    "undisc": "Geothermal",
    "egs": "Geothermal",
    "egs_nearfield": "Geothermal",
    "hydnd": "Hydro",
    "smr": "Nuclear",
    "Demand ": "Demand",
}


volt_line_width = {
    220.0: 0.75,
    230.0: 0.75,
    315.0: 1,
    345.0: 1,
    500.0: 1.25,
    765.0: 1.5,
    735.0: 1.5,
}


def columns_to_simple(input_columns, input_map):
    from difflib import get_close_matches

    rmap = []  # list of tuples
    for column in input_columns:
        results = get_close_matches(column.lower(), list(input_map.keys()))
        if results:
            rmap.append((input_map[results[0]], column))
        # return same value if not mapped
        else:
            rmap.append((column, column))

    return rmap
