"""Shared pytest fixtures for the GAT test suite."""
import os
import warnings
from pathlib import Path
from typing import Optional

import pytest

# Pre-existing v1 breakage (commit 4c765ac): test imports `AggregateDatasetConfig`
# from gat.models.base, but the actual class is `AggregateDataset`. Out of scope
# for the v1-merge task — needs a follow-up to either rename the class or fix
# the import.
collect_ignore = ["test_aggregate_datasets.py"]


@pytest.fixture(autouse=True)
def _silence_legacy_handler_deprecation():
    """Legacy scenario handlers emit DeprecationWarning on instantiation pointing
    users at gat.load(). The tests intentionally exercise the legacy API for
    regression coverage; suppress the warning so it doesn't fail under -W error
    or drown the output."""
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", DeprecationWarning)
        yield

REPO_ROOT = Path(__file__).resolve().parents[1]
HOME = Path(os.path.expanduser("~"))


def _resolve_plexos_root() -> Optional[Path]:
    """Search order for the plexos test fixture directory.

    1. GAT_PLEXOS_FIXTURE env var (CI sets this)
    2. tests/fixtures/plexos/ (committed small fixture, if present)
    3. ~/.gat-test-data/plexos/ (legacy convention)
    4. example_data/plexos/ (in-repo full dataset for local dev)
    """
    candidates = []
    env = os.environ.get("GAT_PLEXOS_FIXTURE")
    if env:
        candidates.append(Path(env))
    candidates.extend([
        REPO_ROOT / "tests" / "fixtures" / "plexos",
        HOME / ".gat-test-data" / "plexos",
        REPO_ROOT / "example_data" / "plexos",
    ])
    for p in candidates:
        if p.is_dir() and any(p.glob("*.h5")):
            return p
    return None


def _resolve_plexos_zip_root() -> Optional[Path]:
    """Search order for a native PLEXOS Solution.zip fixture, used to test
    the plexos2duckdb-backed PlexosDuckDBSystem/PlexosDuckDBSimulation
    (distinct from the h5plexos-converted .h5 fixture above)."""
    candidates = []
    env = os.environ.get("GAT_PLEXOS_ZIP_FIXTURE")
    if env:
        candidates.append(Path(env))
    candidates.extend([
        REPO_ROOT / "tests" / "fixtures" / "plexos_zip",
        HOME / ".gat-test-data" / "plexos_zip",
        REPO_ROOT / "example_data" / "plexos_zip",
    ])
    for p in candidates:
        if p.is_dir() and any(p.glob("*.zip")):
            return p
        if p.is_file() and p.suffix.lower() == ".zip":
            return p
    return None


def _resolve_sienna_root() -> Optional[Path]:
    """Search order for the legacy FileScenario sienna fixture."""
    env = os.environ.get("GAT_SIENNA_FIXTURE")
    candidates = []
    if env:
        candidates.append(Path(env))
    candidates.extend([
        REPO_ROOT / "tests" / "fixtures" / "sienna",
        HOME / ".gat-test-data" / "sienna",
    ])
    for p in candidates:
        if (p / "metadata.json").is_file():
            return p
    return None


def _resolve_sienna_versioned_root(version: str) -> Optional[Path]:
    """Search order for native SiennaScenario fixtures generated by docker/sienna/."""
    env = os.environ.get(f"GAT_SIENNA_V{version.upper().lstrip('V')}_FIXTURE")
    candidates = []
    if env:
        candidates.append(Path(env))
    candidates.append(REPO_ROOT / "example_data" / "sienna" / version)
    for p in candidates:
        if (p / "sys.json").is_file() and (p / "simulation_store.h5").is_file():
            return p
    return None


def _resolve_sienna_multifile_root() -> Optional[Path]:
    """Search order for the two-file Sienna fixture
    (`make sienna-fixture-v4-multi`)."""
    env = os.environ.get("GAT_SIENNA_V4_MULTIFILE_FIXTURE")
    candidates = []
    if env:
        candidates.append(Path(env))
    candidates.append(REPO_ROOT / "example_data" / "sienna" / "v4_multifile")
    for p in candidates:
        if (
            (p / "sys.json").is_file()
            and (p / "simulation_store.h5").is_file()
            and (p / "simulation_store_2.h5").is_file()
        ):
            return p
    return None


@pytest.fixture(scope="session")
def plexos_fixture_root() -> Path:
    root = _resolve_plexos_root()
    if root is None:
        pytest.skip("plexos fixture not available (set GAT_PLEXOS_FIXTURE or populate ~/.gat-test-data/plexos)")
    return root


@pytest.fixture(scope="session")
def plexos_zip_fixture_root() -> Path:
    """A PLEXOS solution .zip (or directory of them) for exercising the
    real plexos2duckdb conversion path end-to-end."""
    root = _resolve_plexos_zip_root()
    if root is None:
        pytest.skip(
            "plexos solution .zip fixture not available "
            "(set GAT_PLEXOS_ZIP_FIXTURE or populate ~/.gat-test-data/plexos_zip)"
        )
    return root


@pytest.fixture(scope="session")
def sienna_fixture_root() -> Path:
    root = _resolve_sienna_root()
    if root is None:
        pytest.skip("sienna fixture not available (Phase 3 — set GAT_SIENNA_FIXTURE or populate ~/.gat-test-data/sienna)")
    return root


@pytest.fixture(scope="session")
def plexos_scenario(plexos_fixture_root):
    from gat.scenariohandlers import PlexosScenario
    s = PlexosScenario(str(plexos_fixture_root))
    s._use_cache = False
    return s


@pytest.fixture(scope="session")
def sienna_scenario(sienna_fixture_root):
    from gat.scenariohandlers import FileScenario
    s = FileScenario(str(sienna_fixture_root))
    s._load_file = "regional_load.pq.gz"
    s._use_cache = False
    return s


@pytest.fixture(scope="session")
def sienna_v4_fixture_root() -> Path:
    root = _resolve_sienna_versioned_root("v4")
    if root is None:
        pytest.skip("sienna v4 fixture not available — run `make sienna-fixture-v4`")
    return root


@pytest.fixture(scope="session")
def sienna_v5_fixture_root() -> Path:
    root = _resolve_sienna_versioned_root("v5")
    if root is None:
        pytest.skip("sienna v5 fixture not available — run `make sienna-fixture-v5`")
    return root


@pytest.fixture(scope="session")
def sienna_v4_scenario(sienna_v4_fixture_root):
    from gat.scenariohandlers import SiennaScenario
    root = sienna_v4_fixture_root
    s = SiennaScenario(
        solution_data=str(root / "simulation_store.h5"),
        system_file=str(root / "sys.json"),
    )
    s._use_cache = False
    return s


@pytest.fixture(scope="session")
def sienna_v5_scenario(sienna_v5_fixture_root):
    from gat.scenariohandlers import SiennaScenario
    root = sienna_v5_fixture_root
    s = SiennaScenario(
        solution_data=str(root / "simulation_store.h5"),
        system_file=str(root / "sys.json"),
    )
    s._use_cache = False
    return s


@pytest.fixture(scope="session")
def sienna_v4_multifile_root() -> Path:
    """Two-file Sienna fixture for exercising the multi-file aggregator
    path. Generated via `make sienna-fixture-v4-multi`. Skip cleanly when
    not present — this fixture is opt-in (~10 min Docker run)."""
    root = _resolve_sienna_multifile_root()
    if root is None:
        pytest.skip(
            "sienna multi-file fixture not available — "
            "run `make sienna-fixture-v4-multi` to generate"
        )
    return root


@pytest.fixture(scope="session")
def sienna_v4_multifile_scenario(sienna_v4_multifile_root):
    """`SiennaScenario` constructed from the two-file fixture, exercising
    the `SimulationAggregator` path."""
    from gat.scenariohandlers import SiennaScenario
    root = sienna_v4_multifile_root
    s = SiennaScenario(
        simulation_files=[
            str(root / "simulation_store.h5"),
            str(root / "simulation_store_2.h5"),
        ],
        system_file=str(root / "sys.json"),
    )
    s._use_cache = False
    return s
