"""Phase 11f — integration + snapshot tests for the multi-file Sienna path.

Exercises `SimulationAggregator(parser_class=SiennaSimulationParser)`
end-to-end via `SiennaScenario(simulation_files=[h5_a, h5_b], ...)` against
the two-file fixture generated by `make sienna-fixture-v4-multi`.

The fixture is built by running PSI's two-stage UC+ED simulation twice
with one-step (24h) overlap between sub-sims. This exercises both:

- **Within-file block dedup** — ED chains many sub-solves with overlapping
  lookahead horizons; the parser must dedup these to a clean time series.
- **Across-file overlap dedup** — the second h5 file's first day overlaps
  with the first h5 file's last day; the aggregator picks the right
  side at the seam.

The two semantics are currently implemented separately
(`SiennaSimulationParser._get_decision_data` for within-file,
`SimulationAggregator._combine_frames` for across-file). The snapshot
tests below pin the *combined* observable output so any future
unification of those two paths can be validated against this baseline.

These tests skip cleanly when the multifile fixture isn't present —
generating it requires a Docker run, so most CI environments won't
have it.
"""

import pandas as pd
import pytest

from gat.simulations import SimulationAggregator


def _flatten(df):
    out = df.copy()
    if isinstance(out.columns, pd.MultiIndex):
        out.columns = ["::".join(str(c) for c in t) for t in out.columns]
    else:
        out.columns = [str(c) for c in out.columns]
    return out[sorted(out.columns)]


def _summary(df):
    flat = _flatten(df)
    numeric = flat.select_dtypes(include="number")
    out = pd.DataFrame(
        {
            "sum": numeric.sum(),
            "min": numeric.min(),
            "max": numeric.max(),
            "mean": numeric.mean(),
        }
    ).reset_index(names="column")
    return out.sort_values("column").reset_index(drop=True)


TOL = {"rtol": 1e-6, "atol": 1e-9}


def test_multifile_scenario_constructs(sienna_v4_multifile_scenario):
    """The scenario's parser is the generic SimulationAggregator (Phase 10b)
    — not the deleted legacy SiennaSimulationAggregator."""
    s = sienna_v4_multifile_scenario
    assert isinstance(s.parser, SimulationAggregator)
    # Aggregator should have exactly two parsers (one per file).
    assert len(s.parser.parsers) == 2


def test_multifile_get_generation_no_duplicate_timestamps(sienna_v4_multifile_scenario):
    """The aggregator's dedup pass should remove the 24h overlap between
    the two sub-simulations. If duplicates leak through, the aggregator
    or its dedup helper is broken."""
    s = sienna_v4_multifile_scenario
    gen = s.get_generation()
    assert isinstance(gen, pd.DataFrame)
    assert not gen.empty
    assert not gen.index.duplicated().any(), (
        "Multi-file generation has duplicate timestamps — "
        "overlap dedup didn't run correctly"
    )


def test_multifile_horizon_spans_union(sienna_v4_multifile_scenario):
    """The combined output should span more time than either single file
    alone — proves the aggregator actually unions the data and isn't
    just returning one file's contents."""
    s = sienna_v4_multifile_scenario
    gen = s.get_generation()
    span_hours = (gen.index.max() - gen.index.min()).total_seconds() / 3600.0
    # Default fixture: 7 days of unique data with 1-day overlap → at least
    # 6 days of distinct horizon. Give a generous lower bound (5 days) to
    # tolerate config tweaks.
    assert (
        span_hours >= 24 * 5
    ), f"Multi-file horizon is only {span_hours:.0f}h; expected ≥120h"


def test_multifile_chronological_index(sienna_v4_multifile_scenario):
    """The aggregator's `sort_index()` finalization should give a
    monotonic-increasing time index even when sub-files are processed
    in any order."""
    s = sienna_v4_multifile_scenario
    gen = s.get_generation()
    assert gen.index.is_monotonic_increasing


# ---------------------------------------------------------------------------
# Snapshot tests — pin the multi-file output so future changes to either
# the within-file dedup (SiennaSimulationParser._get_decision_data) or the
# across-file dedup (SimulationAggregator._combine_frames) are detectable.
#
# Regenerate after `make sienna-fixture-v4-multi`:
#     pytest tests/handlers/test_sienna_multifile.py --force-regen
# ---------------------------------------------------------------------------


def test_multifile_get_generators_tech_snapshot(
    sienna_v4_multifile_scenario, dataframe_regression
):
    """Generator → tech mapping shouldn't change across the multi-file
    aggregator path (system-side data, not simulation-side)."""
    df = sienna_v4_multifile_scenario.get_generators_tech()
    dataframe_regression.check(_flatten(df), default_tolerance=TOL)


def test_multifile_get_generation_summary_snapshot(
    sienna_v4_multifile_scenario, dataframe_regression
):
    """Per-generator generation summary across the combined horizon.

    This is the load-bearing snapshot — captures values *after* both the
    within-file block dedup and the across-file overlap dedup have run.
    A change in either dedup direction will visibly shift the totals
    here."""
    df = sienna_v4_multifile_scenario.get_generation()
    dataframe_regression.check(_summary(df), default_tolerance=TOL)


def test_multifile_get_area_load_summary_snapshot(
    sienna_v4_multifile_scenario, dataframe_regression
):
    """Area-aggregated load is a parameter (not a decision variable),
    so it travels through the dedup path the same as generation but
    with values that aren't sensitive to solver tolerances."""
    df = sienna_v4_multifile_scenario.get_area_load()
    dataframe_regression.check(_summary(df), default_tolerance=TOL)


def test_multifile_get_area_dispatch_summary_snapshot(
    sienna_v4_multifile_scenario, dataframe_regression
):
    """End-to-end: generation + load + curtailment computed across both
    files. Load-bearing for any caller that reads `get_area_dispatch`
    against a multi-file scenario."""
    df = sienna_v4_multifile_scenario.get_area_dispatch(
        include_charging=False,
        include_use=False,
    )
    dataframe_regression.check(_summary(df), default_tolerance=TOL)
