"""Snapshot regression tests for SiennaScenario public API.

Currently covers v4 fixtures generated by `make sienna-fixture-v4`. v5 tests
will be added once the v5 fixture is generated and the `initialize_sienna_config`
v5 branch is in place.

Regenerate snapshots with:
    pytest tests/handlers/test_sienna_regression.py --force-regen
"""

import pandas as pd
import pytest


def _flatten_columns(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    if isinstance(out.columns, pd.MultiIndex):
        out.columns = ["::".join(str(c) for c in tup) for tup in out.columns]
    else:
        out.columns = [str(c) for c in out.columns]
    # Sort columns for deterministic snapshot ordering — column iteration order
    # depends on which scenarios were instantiated earlier in the session.
    return out[sorted(out.columns)]


def _summary(df: pd.DataFrame) -> pd.DataFrame:
    flat = _flatten_columns(df)
    numeric = flat.select_dtypes(include="number")
    out = pd.DataFrame(
        {
            "sum": numeric.sum(),
            "min": numeric.min(),
            "max": numeric.max(),
            "mean": numeric.mean(),
        }
    ).reset_index(names="column")
    # Sort for deterministic ordering — column iteration order depends on
    # which scenarios were instantiated earlier in the session.
    return out.sort_values("column").reset_index(drop=True)


TOL = {"rtol": 1e-6, "atol": 1e-9}


def test_v4_get_generators_tech(sienna_v4_scenario, dataframe_regression):
    df = sienna_v4_scenario.get_generators_tech()
    dataframe_regression.check(_flatten_columns(df), default_tolerance=TOL)


def test_v4_get_gen_and_curtailment_summary(sienna_v4_scenario, dataframe_regression):
    df = sienna_v4_scenario.get_gen_and_curtailment()
    dataframe_regression.check(_summary(df), default_tolerance=TOL)


def test_v4_get_area_dispatch_summary(sienna_v4_scenario, dataframe_regression):
    df = sienna_v4_scenario.get_area_dispatch()
    dataframe_regression.check(_summary(df), default_tolerance=TOL)


def test_v4_get_area_load_summary(sienna_v4_scenario, dataframe_regression):
    df = sienna_v4_scenario.get_area_load()
    dataframe_regression.check(_summary(df), default_tolerance=TOL)


def test_v4_get_area_unserved_contract(sienna_v4_scenario):
    """Sienna doesn't expose unserved energy; the bug-fix code path depends on
    this returning NotImplemented (not a DataFrame, not raising)."""
    assert sienna_v4_scenario.get_area_unserved() is NotImplemented


@pytest.mark.skip(
    reason="v4 fixture uses CopperPlatePowerModel — no line flows produced. Switch generate.jl to DCPPowerModel/PTDF to enable."
)
def test_v4_get_line_loading_summary(sienna_v4_scenario, dataframe_regression):
    df = sienna_v4_scenario.get_line_loading()
    dataframe_regression.check(
        _summary(df), default_tolerance={"rtol": 1e-6, "atol": 1e-3}
    )
