from gat.datahelpers.parsers import *
from .base import BaseScenario
from gat.scenariohandlers.config_maps import *
import warnings
from typing import List, Optional, Union, Dict
import os
from gat.models.scenario import ScenarioConfig, TechnologyMapping, load_config
from gat.quickplots.utils import random_color
from gat.datahelpers.h5Parsers import PlexosParser


# Extensions routed to the v1 duckdb-backed engine — native PLEXOS
# Solution.zip (converted on demand via the optional plexos2duckdb
# dependency) or an already-converted .duckdb file. Everything else
# (".h5") stays on the legacy pandas/h5py path via PlexosParser.
_DUCKDB_LIKE_EXTS = {".zip", ".duckdb"}


def _resolve_plexos_backend_and_files(finder, simulation_files, pattern: str):
    """Classify PlexosScenario's constructor input as the legacy h5
    (pandas/h5py) backend or the v1 duckdb backend, without changing
    resolution for any existing h5 call site.

    ``finder`` is a bound ``self._find_solution_files`` (or any callable
    with the same ``(solution_data, pattern) -> list[str]`` signature),
    passed in rather than closed over so this stays independently testable.

    Resolution order:
      1. No input at all -> ("h5", []) — identical to today's "no parser" case.
      2. Resolve with the caller's own ``pattern`` (default "*.h5"). This is
         the existing, unchanged code path for every current call site (h5
         directories, h5 file lists, h5 globs) — AND it already correctly
         resolves an explicit .zip/.duckdb path or list of them even though
         ``pattern`` defaults to "*.h5": ``BaseScenario._find_solution_files``
         only consults ``pattern`` for directory-globbing and glob-pattern
         strings; explicit file paths resolve via ``os.path.isfile(...)``
         regardless of extension.
      3. If that yields files, classify by extension: all ".h5" -> "h5";
         all in {.zip, .duckdb} -> "duckdb"; mixed -> raise ValueError
         (ambiguous — and a clearer failure than today's undefined
         h5py-crash behavior for genuinely malformed input).
      4. If step 2 found *no* files and the input was a directory/glob
         string (not an explicit file/list, which already tried its best),
         retry with pattern="*.zip" then "*.duckdb" and merge. Only fires
         when h5 resolution found nothing — never overrides a successful
         h5 result.
      5. Still nothing -> ("h5", []) — identical to today.
    """
    if not simulation_files:
        return "h5", []

    resolved = finder(simulation_files, pattern)

    if not resolved:
        zip_candidates = finder(simulation_files, "*.zip")
        duckdb_candidates = finder(simulation_files, "*.duckdb")
        resolved = sorted(set(zip_candidates) | set(duckdb_candidates))
        if not resolved:
            return "h5", []
        return "duckdb", resolved

    exts = {os.path.splitext(f)[1].lower() for f in resolved}
    if exts <= _DUCKDB_LIKE_EXTS:
        return "duckdb", resolved
    if exts == {".h5"}:
        return "h5", resolved

    raise ValueError(
        "PlexosScenario received a mix of file types it cannot route to a "
        f"single backend: {sorted(exts)}. Provide either h5plexos-converted "
        "'.h5' files (legacy pandas/h5py backend) or native PLEXOS "
        "'Solution.zip'/.duckdb files (v1 duckdb backend) — not both in the "
        "same PlexosScenario instance."
    )


class PlexosScenario(BaseScenario):

    """
    Class for interfacing with PLEXOS solutions — either legacy H5 files
    generated by H5PLEXOS.jl, or native PLEXOS ``Solution.zip`` files
    (converted in-process via the optional ``plexos2duckdb`` dependency,
    ``pip install nlr-gat[plexos-duckdb]``). The backend is detected
    automatically from the file extension(s) resolved from
    ``simulation_files`` — every abstract method transparently routes to
    whichever backend was detected; the public API is identical either way.

    Parameters
    ----------
    solution_data : str or List[str], optional
        Path to simulation output data or list of paths to h5 files, OR a
        native PLEXOS ``Solution.zip``/``.duckdb`` path or list of them.
        Can be a directory, single file path, list of file paths, or glob
        pattern. Mixing h5 and zip/duckdb paths in one call raises
        ``ValueError`` — a single instance speaks one backend.
    system_file : str, optional
        Path to system data file (for future use with PLEXOS XML files)
    config : ScenarioConfig, optional
        Configuration object for the scenario
    pattern : str, optional
        Glob pattern to use when searching for files (default: "*.h5").
        Only consulted for directory/glob-string input — explicit file
        path(s) resolve regardless of extension, so this rarely needs
        overriding even for zip/duckdb input (see
        ``_resolve_plexos_backend_and_files``).
    force_convert : bool, optional
        Duckdb backend only (ignored on the h5 backend). Reconvert every
        ``.zip`` input even if a fresh ``.duckdb`` cache already exists.

    Internal Properties
    -------------------
    self.parser : PlexosParser | None
        For reading raw datasets across h5 files. ``None`` on the duckdb backend.
    self._backend : "h5" | "duckdb"
        Which engine this instance is using.
    """
    _expected_model_type = "plexos"

    def _find_solution_files(self, solution_data: Union[str, List[str]], pattern: str = "*.h5") -> List[str]:
        """
        Find PLEXOS solution files (h5 format)

        Parameters:
        -----------
        solution_data : str or list of str
            Path to solution data or list of paths
        pattern : str, optional
            Glob pattern to use when searching for files (default: "*.h5")

        Returns:
        --------
        List[str]
            List of file paths to solution files
        """
        return super()._find_solution_files(solution_data, pattern)

    def __init__(self,
                 simulation_files: Optional[Union[str, List[str]]] = None,
                 system_file: Optional[str] = None,
                 gen_area_map: Optional[dict] = None,
                 load_area_map: Optional[dict] = None,
                 line_rating_map: Optional[dict] = None,
                 config: Optional[ScenarioConfig] = None,
                 pattern: str = "*.h5",
                 # Deprecated alias — use simulation_files instead
                 solution_data: Optional[Union[str, List[str]]] = None,
                 # Alias used by gat.loader for v1 PlexosScenarioConfig.solution_path
                 solution_path: Optional[Union[str, List[str]]] = None,
                 # v1 duckdb backend only — ignored on the h5 backend.
                 force_convert: bool = False,
                 ) -> None:
        """
        Initialize a PlexosScenario object with configuration, system data, and solution data.

        Parameters:
        -----------
        simulation_files : str or list of str, optional
            Path to simulation output data or list of paths to h5 files,
            OR a native PLEXOS Solution.zip/.duckdb path or list of them.
        system_file : str, optional
            Path to system data file (for future use with PLEXOS XML files)
        gen_area_map : dict, optional
            Mapping from generator IDs to geographic areas
        load_area_map : dict, optional
            Mapping from load IDs to geographic areas
        line_rating_map : dict, optional
            Mapping from line IDs to line capacities
        config : ScenarioConfig, optional
            Configuration object for the scenario
        pattern : str, optional
            Glob pattern to use when searching for files (default: "*.h5")
        solution_data : str or list of str, optional
            Deprecated. Use ``simulation_files`` instead.
        force_convert : bool, optional
            v1 duckdb backend only. Reconvert every ``.zip`` input even if
            a fresh ``.duckdb`` cache already exists next to it.
        """
        from ._deprecation import warn_legacy_handler
        warn_legacy_handler(self)
        from .base import _resolve_simulation_files

        # `solution_path` is the v1 alias for `simulation_files`.
        if solution_path is not None and simulation_files is None:
            simulation_files = solution_path
        simulation_files = _resolve_simulation_files(simulation_files, solution_data)

        # Create a default config if none provided
        if config is not None and isinstance(config, str):
            self.config = load_config(config)
        elif config is not None:
            self.config = config
        else:
            self.config = ScenarioConfig(model_type=self._expected_model_type)

        # Store system path if provided
        if system_file is not None:
            self.config.system_path = system_file

        # Default tech mapping for PLEXOS
        self._tech_simple = plexos_map_simple

        # Detect which backend this instance speaks (h5 vs native
        # zip/duckdb) and resolve the file list accordingly. This never
        # changes resolution for existing h5 callers — see
        # _resolve_plexos_backend_and_files's docstring.
        self._backend, self._solution_files = _resolve_plexos_backend_and_files(
            self._find_solution_files, simulation_files, pattern
        )
        if self._solution_files:
            self.config.simulation_paths = self._solution_files

        self.parser = None
        self._duckdb_system = None
        self._duckdb_sim = None

        if self._backend == "duckdb":
            from ..simulations.plexos_duckdb import PlexosDuckDBSimulation
            from ..systems.plexos_duckdb import PlexosDuckDBSystem
            self._duckdb_system = PlexosDuckDBSystem(
                self._solution_files, force_convert=force_convert
            )
            self._duckdb_sim = PlexosDuckDBSimulation(
                self._solution_files, force_convert=force_convert
            )
        elif self._solution_files:
            # Initialize parser if solution files are available
            self.parser = PlexosParser(solution_files=self._solution_files)

        # Call parent initialization to set up config and find files
        super().__init__(
            simulation_files=simulation_files,
            gen_area_map=gen_area_map,
            load_area_map=load_area_map,
            line_rating_map=line_rating_map,
            config=self.config,
            system_data=system_file,
            pattern=pattern
        )

        if self._backend == "duckdb":
            if not self._tech_map:
                self._tech_map = self.generator_technology_map
            if not self._gen_area_map:
                self._gen_area_map = self._duckdb_system.source.membership_map(
                    parent_class="Region", child_class="Generator"
                )
            if not self._load_area_map:
                # Regions ARE the areas for load aggregation by default —
                # mirrors the h5 path's get_h5_region_region_map identity map.
                regions = self._duckdb_system.get_dataset("Region")
                self._load_area_map = {name: name for name in regions["name"]}
            try:
                if not self._line_rating_map:
                    self._line_rating_map = self.generate_line_rating_map()
            except Exception as e:
                warnings.warn(f"Unable to initialize line rating metadata: {e}. Please self assign object property.")
        # Initialize maps from parser if available
        elif self.parser:
            # Generate maps from the parser if not provided
            if not self._tech_map:
                self._tech_map = self.generator_technology_map()
            if not self._gen_area_map:
                self._gen_area_map = self.generate_gen_area_map()
            if not self._load_area_map:
                self._load_area_map = self.generate_map(get_h5_region_region_map)
            try:
                if not self._line_rating_map:
                    self._line_rating_map = self.generate_line_rating_map()
            except Exception as e:
                warnings.warn(f"Unable to initialize line rating metadata: {e}. Please self assign object property.")

        # Set additional attributes
        self._load_includes_charging = False



    def generate_map(self, map_generator)->dict:
        """Generates a dictionary relationship"""
        map = {}

        for file in self.config.simulation_paths:
            map_instance = map_generator(file)
            map.update(map_instance)
        return map

    def generate_gen_area_map(self)->dict:

        """
        Generates the generator technology map. Checks if 'batteries' is found in the h5 ST/interval group.
        If so appends the battery->tech map into the overall generator-tech map.
        """
        generator_area_map = self.parser.get_metadata('metadata/relations/regions_generators', reverse=True)
        if 'batteries' in self.parser.list_groups('ST','interval'):
            battery_area_map = self.parser.get_metadata('metadata/relations/regions_batteries', reverse=True)
            return generator_area_map | battery_area_map
        else:
            return generator_area_map

    @property
    def generator_technology_map(self)->Dict[str,str]:

        """
        Generates the generator technology map. Checks if 'batteries' is found in the h5 ST/interval group.
        If so appends the battery->tech map into the overall generator-tech map.

        On the v1 duckdb backend, reads the Generator class's own
        ``category`` column directly — no battery union needed (PLEXOS
        Storage objects are internal head/tail bookkeeping for
        battery-capable generators, not separately-categorized entities;
        see gat/systems/plexos_duckdb.py for the full explanation).
        """
        if self._backend == "duckdb":
            gens = self._duckdb_system.get_dataset("Generator")
            return dict(zip(gens["name"], gens["category"]))

        generation_tech = self.parser.get_metadata(h5_path='metadata/objects/generators')
        if 'batteries' in self.parser.list_groups('ST','interval'):

            battery_tech = self.parser.get_metadata(h5_path='metadata/objects/batteries')
            return generation_tech | battery_tech
        else:
            return generation_tech

    def generate_line_rating_map(self, frequency='year')->dict:

        """
        **PLEXOS Dataset: /ST/year/lines/Export Limit**

        Parses the line capacity dataset to populate self._line_rating_map

        :returns: Dictionary of {Line ID: Line capacity}
        """
        if self._backend == "duckdb":
            return self._duckdb_system.get_branch_ratings()

        return self.parser.get_h5dataset('ST',frequency,'lines', 'Export Limit').droplevel('category').T.iloc[0].to_dict()


    def get_generation(self)->pd.DataFrame:
        """
        **PLEXOS H5 Datset Path:  /ST/interval/generators/Generation**

        :returns: Timeseries of the generation across one or multiple h5 files
        """
        if self._backend == "duckdb":
            return self._duckdb_sim.get_dataset("generation")

        generation = self.parser.get_h5dataset('ST', 'interval','generators', 'Generation')
        generation = generation.droplevel('category')
        if 'batteries' in self.parser.list_groups("ST",'interval'):

            battery_generation = self.parser.get_h5dataset('ST', 'interval','batteries', 'Generation')
            battery_generation = battery_generation.droplevel('category')
            battery_generation.index.name = 'generators'

            all_generation = pd.concat([generation, battery_generation]).drop_duplicates()
            return all_generation.T

        else:
            return generation.T

    def get_availability(self)->pd.DataFrame:
        """
        **PLEXOS H5 Dataset Path: /ST/interval/generators/Available Capacity**

        :returns: Timeseries of the VRE availability across one or multiple h5 files. Used in Curtailment calculations.
        """
        if self._backend == "duckdb":
            return self._duckdb_sim.get_dataset("availability")

        result = self.parser.get_h5dataset('ST', 'interval','generators', 'Available Capacity')
        result = result.droplevel('category')
        return result.T

    def get_line_flow(self)->pd.DataFrame:
        """
        **PLEXOS H5 Dataset Path: /ST/interval/Lines/Flow**

        :returns: Timeseries dataframe of the line flow across one or multiple h5 files.
        """
        if self._backend == "duckdb":
            return self._duckdb_sim.get_dataset("line_flow")

        flow = self.parser.get_h5group('ST','interval', 'lines', datasets=['Flow'], plexos_format=False)
        flow = flow.droplevel(['dataset', 'category']).T
        return flow


    def get_load(self)->pd.DataFrame:
        """
        **PLEXOS H5 Dataset Path: /ST/interval/regions/Load**

        :returns: Timeseries dataframe of the load by region.

        """
        if self._backend == "duckdb":
            try:
                return self._duckdb_sim.get_dataset("load")
            except KeyError:
                return None

        # Need to understand whether Load, Native Load or both are provided.
        result = self.parser.get_h5dataset('ST', 'interval','regions', 'Load')
        result = result.droplevel('category')
        return result.T

    def get_unserved(self)->pd.DataFrame:
        """
        **PLEXOS H5 Dataset Path: /ST/interval/regions/Unserved Energy**

        :returns: Timeseries dataframe of unserved energy by region.
        """
        if self._backend == "duckdb":
            try:
                return self._duckdb_sim.get_dataset("unserved")
            except KeyError:
                return NotImplemented

        result = self.parser.get_h5dataset('ST', 'interval','regions', 'Unserved Energy')
        result = result.droplevel('category')
        return result.T

    def get_generation_capacity(self)->pd.DataFrame:
        """
        **PLEXOS H5 Dataset Path: /ST/year/generators/Installed Capacity**

        Reads only first file in the list of h5 files

        :returns: Dataframe of capacity by Area and Technology.

        """
        if self._backend == "duckdb":
            df = self._duckdb_sim.get_dataset("ST__Year__Generators__Installed_Capacity")
            capacities = df.iloc[0]
            idx = pd.MultiIndex.from_tuples([(
                self._map_gen_to_area(gen),
                self._map_gen_to_tech(gen),
                gen) for gen in capacities.index], names=['Area', 'Technology', 'Generator'])
            capacities = pd.Series(capacities.values, index=idx)
            return capacities.groupby(level=['Area', 'Technology']).sum().unstack(level='Technology').fillna(0.0)

        df = self.parser.get_h5dataset('ST','year','generators','Installed Capacity', template=True)
        df = df.droplevel('category')
        df.index = pd.MultiIndex.from_tuples([(
        self._map_gen_to_area(idx),
        self._map_gen_to_tech(idx),
        idx) for idx in df.index], names=['Area', 'Technology', 'Generator'])

        return df.groupby(level=['Area', 'Technology']).sum().unstack(level='Technology').droplevel(0, axis=1).fillna(0.0)

    def get_storage_charging(self)->pd.DataFrame:

        """
        **PLEXOS H5 Dataset: /ST/interval/storages/Pump Load**

        :returns: Timeseries Dataframe of Pump load by generator.

        """
        if self._backend == "duckdb":
            try:
                df = self._duckdb_sim.get_dataset("storage_charging")
            except KeyError:
                return None
            # Storage objects are named "<generator>_head"/"<generator>_tail"
            # (PLEXOS's internal reservoir bookkeeping) — only "_head"
            # carries the real charging value on this data model (verified:
            # "_tail" is always 0), same convention the h5 path already uses.
            sub_cols = [col for col in df.columns if col.endswith('_head')]
            df = df[sub_cols]
            df.columns = [col[:-len('_head')] for col in df.columns]
            return df

        df = self.parser.get_h5dataset('ST', 'interval','storages', 'Pump Load')
        df = df.droplevel('category')
        df = df.T
        # just get the _head columns
        sub_cols = [col for col in df.columns if col.endswith('_head')]
        df = df[sub_cols]
        df.columns = [col.replace('_head','') for col in df.columns]
        return df

    # TODO, this doesn't seem to be working
    def get_production_cost(self, zone=None) -> pd.DataFrame:

        """ gets the production cost for a specific region, broken down by cost type
            #TODO: add datetime slicing capability
        """
        if self._backend == "duckdb":
            try:
                df = self._duckdb_sim.get_dataset("production_cost")
            except KeyError:
                return NotImplemented
            if zone is not None:
                cols = [c for c in df.columns if self._map_gen_to_area(c) == zone]
                df = df[cols]
            return df

        Warning.warn("Warning get_raw_production_cost_annual is experimental and subject to change in the future.")
        cost_cats = pd.DataFrame({'Fuel Cost' : 0,
                    'VO&M Cost': 0,
                    'UoS Cost' : 0,
                    'Start & Shutdown Cost' : 0
                        })

        gen_datasets = self.parser.list_datasets('ST','interval','generators')


        for cat in cost_cats.keys():
            if cat in gen_datasets:
                d = self.get_gen_dataset(cat).sum().sum() / 1000 #Annual sum, convert to millions. (Raw values are in $1000s)
                cost_cats.loc[cat] = d
        return cost_cats



    def get_plexos_h5map(self, h5path)->dict:
        """Parses a relationship dataset found in the h5 files

        :param h5path: example /relations/generator_region

        """
        return parse_h5_map(self._template_file, h5path)

    def set_area_map(self, area_map: str ) -> None:
        """
        Sets the load->area and generator->area mapping based on available relations in the h5 dataset.

        :param area_map: 'zone' or 'region'

        """

        if area_map.lower() == 'zone':
            self._gen_area_map = get_h5_gen_zone_map(self._template_file)
            self._load_area_map = get_h5_region_zone_map(self._template_file)
        elif area_map.lower() == 'region':
            self._gen_area_map = get_h5_gen_region_map(self._template_file)
            self._load_area_map = get_h5_region_region_map(self._template_file)


